// Generated by https://quicktype.io

export interface ListadoCategorias {
  total: number;
  categorias: Categoria[];
}

export interface Categoria {
  _id: string;
  name: string;
  descripcion?: string;
  state?: boolean;
  img?: string;
  usuario: Usuario;
}

export interface Usuario {
  _id: string;
  name: string;
}
