// Generated by https://quicktype.io

export interface ProductoListado {
  total: number;
  productos: Producto[];
}

export interface Producto {
  _id: string;
  name: string;
  descripcion: string;
  img?: string;
  precio: number;
  stock_min: number;
  cantidad: number;
  disponible: boolean;
  categoria: Almacen;
  almacen: Almacen;
  proveedor: Almacen | null;
  usuario: Almacen;
}

export interface Almacen {
  _id: string;
  name: string;
}
