// Generated by https://quicktype.io

export interface ProductoListado {
  total: number;
  productos: Producto[];
}

export interface Producto {
  _id: string;
  name: string;
  descripcion: string;
  img?: string;
  precio: number;
  stock_min: number;
  cantidad: number;
  disponible: boolean;
  categoria: Almacen;
  almacen: Almacen;
  proveedor: Almacen | null;
  usuario: Almacen;
}

export interface Almacen {
  _id: string;
  name: string;
}

// Generated by https://quicktype.io

export interface ItemProduct {
  result: Result;
}

export interface Result {
  itemsList: ItemsList[];
  total: number;
  limit: number;
  totalPages: number;
  page: number;
  pagingCounter: number;
  hasPrevPage: boolean;
  hasNextPage: boolean;
  prevPage: null;
  nextPage: null;
}

export interface ItemsList {
  stock_min: number;
  _id: string;
  name: string;
  descripcion: string;
  img: string;
  precio: number;
  cantidad: number;
  disponible: boolean;
  categoria: null;
  almacen: Almacen;
  proveedor: Almacen;
  usuario: Almacen;
  created_at: string;
}

export interface Almacen {
  _id: string;
  name: string;
}
